### ISSUE TITLE
Touching out of "Touchpad Area" makes cursor move in vanilla behavior

### ISSUE THREAD

**Issue by MeerukYang** [lingrottin/MapTP#1]
![image](https://github.com/lingrottin/MapTP/assets/146934099/5de21ddf-89a3-41a2-802e-870218187440)
If "Touchpad Area" being not fully used, Then touching the area this image shows would not input absolutely as the cursor will still act as in vanilla behavior.
It makes coutinuous pad-touch movement transferred into a non-continuous cursor movement if cross the borderline back and forth, which is annoying.

**Comment by lingrottin** [comment]
确实存在这个问题，因为 MapTP 并没有做到屏蔽触摸板输入。当映射启用时，触摸板产生的光标相对移动信息会立即被绝对坐标覆盖掉，从而造成触摸板输入被屏蔽了的假象。

btw. 我曾经找过屏蔽触摸板输入的方法，最终还是不了了之。如果能屏蔽触摸板输入就自然能解决这个问题了。

**Comment by lingrottin** [comment]
已经解决了。现在，手指越界的行为是光标在屏幕映射区域的边缘滑动。
