### ISSUE TITLE
如何解决灰色按钮start mapping问题

### ISSUE THREAD

**Issue by jackeyloveseven** [lingrottin/MapTP#2]
![Quicker_20231224_151830](https://github.com/lingrottin/MapTP/assets/111408747/e26c1030-b99b-4cfe-ad8c-74e871fb5005)

**Comment by lingrottin** [comment]
很抱歉回复得比较晚。这个情况大概是触摸板的映射区域设置不合理。我注意到上方的触摸板示意图是条形的，所以可能是触摸板尺寸校准出了错误。你可以
* 在 Windows 文件资源管理器里打开 `%HOMEPATH%\AppData\Local\cn.enita.MapTP` 并删除 `config.xml`
* 重新打开 MapTP，点击 Calibrate 按钮
* **用手指点击触摸板的*右下角*（请让手指在附近滑一会儿），按下 Enter**
* 点击 Suggest mapping size
* Start Mapping 应该可以点了。（如果还是不行，手动调整 Touchpad area 内的映射数值试试）
如果还是解决不了，请告诉我。
（如果你的触摸板确实是条形的，请务必让我知道）

**Comment by jackeyloveseven** [comment]
非常感谢能用了，祝您学业顺利生活愉快



---原始邮件---
发件人: "Tienyu ***@***.***&gt;
发送时间: 2023年12月24日(周日) 晚上11:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lingrottin/MapTP] 如何解决灰色按钮start mapping问题 (Issue #2)




 
很抱歉回复得比较晚。这个情况大概是触摸板的映射区域设置不合理。我注意到上方的触摸板示意图是条形的，所以可能是触摸板尺寸校准出了错误。你可以
  
在 Windows 文件资源管理器里打开 %HOMEPATH%\AppData\Local\cn.enita.MapTP 并删除 config.xml
 
重新打开 MapTP，点击 Calibrate 按钮
 
用手指点击触摸板的右下角（请让手指在附近滑一会儿），按下 Enter
 
点击 Suggest mapping size
 
Start Mapping 应该可以点了。（如果还是不行，手动调整 Touchpad area 内的映射数值试试）
 如果还是解决不了，请告诉我。
 （如果你的触摸板确实是条形的，请务必让我知道）
