### ISSUE TITLE
针对绘画的新功能提议

### ISSUE THREAD

**Issue by mywarframe** [lingrottin/MapTP#3]
您好！我对您的MapTP这款应用很感兴趣，但是请问该如何启动这款应用，网上千篇一律地说要看readme，然后......我就来这里了，请您在空闲之余给予帮助，谢谢！

**Comment by lingrottin** [comment]
抱歉，没有写 README 是我的问题。  
你可以在页面上的 releases 界面下载压缩包并解压，里面的 exe 文件应该能直接运行。  
注意，此应用使用了 Windows 10 及以上的“精确式触控板”功能
还有其他问题可以单独开一个 issue。

**Comment by mywarframe** [comment]
这个问题已经解决了，谢谢！那个，我没学过编程，要是太困难就忽略吧：
提案一：省流：让触摸板移动光标时，默认是选中不松的
详情：我想用MapTP来让触摸板充当数位板的功能，但是在PS绘图时需要快速双击后按住才能绘画，因为触摸板很小，两次点击位置有细微的差别就会导致大的偏差，所以能不能给MapTP加一个功能，就是用触摸板移动光标的话，是默认按住不放的，如果用鼠标（或外接设备的输入）移动的话，光标是正常的，类似于将触摸板的单击等效于双击吧。（让我也来助一份力吧，名字已经帮你想好了，MapTP-T，turtle模式，乌龟这玩意儿咬住就不松口）
或提案二：省流：缩小Map范围，且位置可移动
详情：在看了“inklet 2 for Mac”的设计后,要是有一个大小等于触摸板大小的判定框，可以通过鼠标拖动来移动位置（当然固定在屏幕正中央也可以，我可以拖动画布来改变相对位置），这样的话，就算双击后有细微的偏差也不会有太大的影响。（MapTP-Z，Zion模式，机动战士敢达中吉翁的机体都是独眼取景的，感觉很像哎）
或提案三（recommended）：我都~要[doge]（MapTP-SB,shameless behavior)
或提案四：从第一行第13个字开始忽略后续内容

**Comment by lingrottin** [comment]
因为开发这玩意的初衷是用触摸板玩 osu! 所以没有想这么多，但是我可以研究一下。

**Comment by mywarframe** [comment]
有劳了！

**Comment by lingrottin** [comment]
已经大概做好了，但是笔记本不在身边所以没有测试。烦请到 Release 界面下载最新的 pre-release 文件试一下。;D
https://github.com/lingrottin/MapTP/releases/tag/v1.0.0_3

**Comment by mywarframe** [comment]
![屏幕截图(33)](https://github.com/lingrottin/MapTP/assets/161032804/fd4a6692-ff6d-4fd4-a7bc-888802d987de)
![屏幕截图(34)](https://github.com/lingrottin/MapTP/assets/161032804/5fc9f355-8e70-48a6-a7f3-5f12d02a389c)
新版本无法独自运行，不开插件也一样，但是如果把旧版本开启，launch inspector就可以正常工作了，此时两个版本的映射位置旧版本优先，两个版本在不断的重启过程中有一定概率会相互对应（发生过两次）此外新版本的判定框会随机出现在左上角
![屏幕截图(35)](https://github.com/lingrottin/MapTP/assets/161032804/c5cf89dd-7915-44cd-ac4e-0f2361fa8b3e)
![屏幕截图(36)](https://github.com/lingrottin/MapTP/assets/161032804/45de2a4e-b975-4ea1-9534-d8d22d3f77fd)
![屏幕截图(37)](https://github.com/lingrottin/MapTP/assets/161032804/206c8c88-b541-495b-a1b7-eeeda306836d)
![屏幕截图(38)](https://github.com/lingrottin/MapTP/assets/161032804/33b5751e-8c7d-48c5-bcb3-10df91fad7ec)
![屏幕截图(39)](https://github.com/lingrottin/MapTP/assets/161032804/6ab1489a-e853-4e2d-8d7c-01e7d4d44309)
但是实际范围还是以旧版本为主，turtle mode在旧版开启的情况下也不会生效

**Comment by lingrottin** [comment]
映射区域共享应该是因为配置文件是写死在代码里的，这个没有什么影响。
可以描述一下单独开启新版本出现的现象嘛

**Comment by lingrottin** [comment]
问题似乎在于我为 Tip 数据指定了错误的 UsagePage 值，导致应用不能从触摸板读取输入。我会在明天中午试着改一下，并再编译一份放上来。

**Comment by lingrottin** [comment]
改好了，麻烦再看一下最新的 pre-release。
https://github.com/lingrottin/MapTP/releases/tag/1.0.0_4
为此带来的不便抱歉（）

**Comment by mywarframe** [comment]
抱歉，最近开学了，只能晚上放学后才能回复
![屏幕截图(40)](https://github.com/lingrottin/MapTP/assets/161032804/d43497c0-cbcb-4087-9780-a790fa27b77c)
版本4和版本3一样，独自运行时没有任何反应，不打开附加功能也一样，发起判定框后，screen area显示的范围和位置与判定框的范围和位置吻合，但是用触摸板移动光标时，TP功能并没有实现；在测试Calibrate touchpad size功能时，多次触摸触控板右下角并无反应，手指在整个触摸板上任意滑动和点击也无反应，而suggest mapping size始终有效。（会不会是turtle mode的原因？它的存在干扰了程序对设备的检测？或许先删除这个功能再试试。）

https://github.com/lingrottin/MapTP/assets/161032804/7fdc0ebe-e4da-451e-9f20-1ace25127eb2
（题外话，
![屏幕截图(41)](https://github.com/lingrottin/MapTP/assets/161032804/ee5386ce-390c-4c2a-8bb8-bfa6b74e547b)
![屏幕截图(42)](https://github.com/lingrottin/MapTP/assets/161032804/2d91c300-db8e-4d45-8f00-6bb32663ed2b)
您在编程时使用的是哪一种语言呢，如果想要零基础自学编程，以能看懂为目的，应该从free code camp上哪一门课程开始学呢，或是有更好的选择？能推荐适合于毫无基础的人学习概念的教材吗？如果造成困扰十分抱歉，还请忽略。）

**Comment by lingrottin** [comment]
没事 我也开学了（）
看起来还是 Tip Switch 数据的问题，但是我这里也不太好测试。我会再研究一下的。
MapTP 使用的是 C# + WPF 框架，剩下的问题不适合在 issue 里讨论，感兴趣的话可以用邮件索要我的 QQ 号。

**Comment by lingrottin** [comment]
#7 之后解决这里提出的 Turtle mode 就容易多了。容我再琢磨一下（

**Comment by lingrottin** [comment]
事隔 7 个月终于做好了！（
