### ISSUE TITLE
Pre-Release v1.0.0_4 似乎不能正常工作

### ISSUE THREAD

**Issue by zhzhongshi** [lingrottin/MapTP#4]
我最近有绘图需求，看到了这个项目，但是这个v1.0.0 _2指针抖动似乎很厉害，看到 #3 有提到，我试了现在好像并不能单独运行。。

**Comment by lingrottin** [comment]
抱歉哦，1.0.0_4 是不能用的。因为当时没有把问题解决好，后来就搁置了（）当时有一个设想是实现“触摸触摸板时按下鼠标 放开时松开”，最终是对 API 的理解有问题，所以造成了那个不能用的版本。可以暂时用着 v1.0.0_2（）

另：MapTP 一直都没有设计防抖功能，我放假之后（2w 左右）可以做一做（）现在时间太紧了（）

这个 issue 先保持开着吧（）

**Comment by lingrottin** [comment]
还有就是 fork 的话建议从 9ff5024 开始改，因为从那之后的 commit 就被我做成不能用的了（）

**Comment by lingrottin** [comment]
#3 中的绘画优化功能已经实现了，但是防抖还是有点难度（）  
超出能力范围了，抱歉（
