### ISSUE TITLE
使用 Paint.net 软件绘图时出现严重延迟，原因不明

### ISSUE THREAD

**Issue by RxinnotRstar** [lingrottin/MapTP#5]
- 使用 [Paint.net](https://getpaint.net)

> - Using [Paint.net](https://getpaint.net)

- [x] 鼠标涂写-无严重延迟

> - [x] Mouse drawing - No significant delay

- [x] 原生触摸板涂写-无严重延迟

> - [x] Native touchpad drawing - No significant delay

- [ ] 映射触摸板涂写-无严重延迟

> - [ ] Mapped touchpad drawing - No significant delay

- 对照组 · 使用 [Microsoft Whiteboard](https://www.microsoft.com/store/productId/9MSPC6MP8FM4)

> - Control group: Using [Microsoft Whiteboard](https://www.microsoft.com/store/productId/9MSPC6MP8FM4)

- [x] 鼠标涂写-无严重延迟

> - [x] Mouse drawing - No significant delay

- [x] 原生触摸板涂写-无严重延迟

> - [x] Native touchpad drawing - No significant delay

- [x] 映射触摸板涂写-无严重延迟

> - [x] Mapped touchpad drawing - No significant delay

我录了一段遇到延迟情况的视频：

> I have recorded a video demonstrating the delay issue:

https://github.com/user-attachments/assets/985e6661-599c-4d73-9048-f7f22c5c856b

**Comment by lingrottin** [comment]
原因可能是单位时间内的鼠标移动事件太多了？
MapTP 的工作原理是

接收到触摸板输入 -> 计算并发布绝对坐标输入事件

也就是说这个过程中目标软件会接收到
* 原生的触摸板输入事件
* 经过 MapTP 处理的绝对输入事件

换句话说，使用了 MapTP，会导致光标输入的频率是实际触摸板报告率的两倍。（因为我没有找到阻断触摸板输入事件的方法）

以上只是一个猜测。按照这个猜测，问题应该出在 Paint.NET 软件的性能问题而不是 MapTP 本身。具体的解决方案和问题的真正原因我也不太明白。或许可以用 Visual Studio 来 debug 一下 Paint.NET 看看？

**Comment by RxinnotRstar** [comment]
> 原因可能是单位时间内的鼠标移动事件太多了？ MapTP 的工作原理是
> 
> 接收到触摸板输入 -> 计算并发布绝对坐标输入事件
> 
> 也就是说这个过程中目标软件会接收到
> 
>     * 原生的触摸板输入事件
> 
>     * 经过 MapTP 处理的绝对输入事件
> 
> 
> 换句话说，使用了 MapTP，会导致光标输入的频率是实际触摸板报告率的两倍。（因为我没有找到阻断触摸板输入事件的方法）
> 
> 以上只是一个猜测。按照这个猜测，问题应该出在 Paint.NET 软件的性能问题而不是 MapTP 本身。具体的解决方案和问题的真正原因我也不太明白。或许可以用 Visual Studio 来 debug 一下 Paint.NET 看看？

我先去官方论坛提问一下吧……希望官方论坛有大佬能帮助解答。

https://forums.getpaint.net/topic/130520-issue-with-maptp-software-causing-delay-in-paintnet-drawing/

- 
>
> > The reason might be that there are too many mouse movement events within a unit of time? The working principle of MapTP is as follows:
> >
> > Receive touchpad input -> Calculate and publish absolute coordinate input events
> >
> > In other words, during this process, the target software will receive:
> >
> >     * Native touchpad input events
> >     * Absolute input events processed by MapTP
> >
> > In other words, using MapTP will double the frequency of cursor input compared to the actual touchpad reporting rate. (Because I haven't found a way to block touchpad input events).
> >
> > The above is just a hypothesis. Following this hypothesis, the issue should lie within the performance of the Paint.NET software rather than MapTP itself. I am not entirely clear on the specific solution and the true cause of the problem. Perhaps you can use Visual Studio to debug Paint.NET and investigate further?
>
> I'll go to the official forum to ask... Hopefully, there are experts on the forum who can help provide some answers.
>

**Comment by lingrottin** [comment]
简单研究了一下，成果是精确式触摸板（PTP）属于排他（exclusive）类的 HID 设备。

![Image_1727772673313.png](https://github.com/user-attachments/assets/a1b336b6-9ecb-4f45-87ed-15319448acbe)

![Image_1727772676843.png](https://github.com/user-attachments/assets/cda1eb07-8b74-49e2-8e19-72ed06205c53)

这意味着 MapTP 作为*应用程序*，很可能无法做到对触摸板事件“捕捉并截断传播”。解决方法可能涉及到对 Windows 内核层的改动，但是我能力不足，万分抱歉（
